language: php

php:
  - 5.6
  - 7.3
  
matrix:
  allow_failures:

env:

before_script:
 - curl http://cs.sensiolabs.org/get/php-cs-fixer.phar -o php-cs-fixer.phar
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install --no-interaction --prefer-source

script:
 - mkdir -p build/logs
 - phpunit --configuration ./test/phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v --exclude-no-stmt
